name: check_new_version
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install dxpy
        pipenv install --dev
    - name: List files in the repository
      run: |
       ls ${{ github.workspace }}
    # - name: Upload to DNAnexus
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.DX_TOKEN }}
