name: check_new_version
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install dxpy
    # - name: List files in the repository
    #   run: |
    #     CONDUCTOR_CONFIG=$(ls ${{ github.workspace }} *.json)
    #     echo $CONDUCTOR_CONFIG
    #     echo "CONDUCTOR_CONFIG=$CONDUCTOR_CONFIG" >> $GITHUB_ENV
    - name: Upload to DNAnexus
      # env:
      #   conductor_config: ${{ env.CONDUCTOR_CONFIG }}
      run: |
        dx upload eggd_conductor_dias_TWE_config_v2.0.0.json --token ${{ secrets.DX_TOKEN }} --destination 003_240229_GitHub_Actions_testing:/
