name: check_new_version
on:
  pull_request:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed files
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install dxpy packaging

      - name: Get changed JSON files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.json

      - name: Upload changed JSON files
        if: steps.changed-files.outputs.any_changed == 'true'
        env: 
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          dx login --token ${{ secrets.DX_TOKEN }}
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed in this PR"
            FILE_ID=$(dx upload $file --destination 003_240229_GitHub_Actions_testing:/ --brief)
            echo "uploaded file ID is $FILE_ID"
          done
      - name: Run Python script
        env: 
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          python perform_testing.py -i ${ALL_CHANGED_FILES}
