name: check_new_version
on:
  pull_request:
    branches:
      - main

jobs:
  upload_and_test:
    runs-on: ubuntu-latest
    name: Upload and test changed files
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Get changed JSON files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.json

      - name: Upload changed JSON files to DNAnexus
        id: changed-config
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          dx login --token ${{ secrets.DX_TOKEN }}
          echo "${CHANGED_FILES} was changed in this PR"
          FILE_ID=$(dx upload ${CHANGED_FILES} --destination ${{ vars.TESTING_PROJECT }}:/ --brief)
          echo "Config file uploaded. File ID: $FILE_ID"
          echo "FILE_ID=$FILE_ID" >> $GITHUB_OUTPUT

      - name: Run Python script
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          FILE_ID: ${{ steps.changed-config.outputs.FILE_ID }}
        run: |
          echo ${ALL_CHANGED_FILES}
          echo ${FILE_ID}
          python perform_testing.py -i ${ALL_CHANGED_FILES} -f ${FILE_ID}
